import { useState, useEffect, useRef, useCallback } from 'react';
import { Upload, Download, Type, Image as LucideImage, ZoomIn, Palette, Check, Move, RotateCw, Droplet, Coffee, RotateCcw, X, ChevronDown, Circle, Undo2, Redo2, BookmarkPlus, Bookmark, Trash2, Info, Maximize2 } from 'lucide-react';
import { Analytics } from '@vercel/analytics/react';

const TRANSLATIONS = {
  it: {
    subtitle: 'Crea icone cartella macOS personalizzate.',
    section1: '1. Grafica',
    folderStyle: 'Stile cartella',
    folderColor: 'Colore cartella',
    cassetteColor: 'Colore cassetta',
    defaultColor: 'Default',
    changeImage: 'Cambia immagine',
    uploadImage: 'Carica Immagine',
    uploadFormats: 'JPG, PNG, WEBP',
    zoom: 'Zoom',
    rotation: 'Rotazione',
    section2: '2. Etichetta',
    styleDymo: '🏷️ Dymo',
    styleBanner: '▬ Fascia',
    styleBadge: '● Badge',
    labelText: 'Testo (lascia vuoto per nascondere)',
    labelPlaceholder: 'Es. Progetto X',
    font: 'Font',
    fontSize: 'Dimensione testo',
    tapeSize: 'Dimensione nastro',
    badgeSize: 'Dimensione badge',
    tapeAngle: 'Inclinazione nastro',
    resetTip: 'Ripristina',
    resetBtn: 'reset',
    dragHint: "Trascina l'etichetta in anteprima per riposizionarla",
    colorTape: 'Colore Nastro',
    colorBanner: 'Colore Fascia',
    colorBadge: 'Colore Badge',
    opacity: 'Opacità',
    download: 'Scarica',
    downloadPng: 'PNG 1024×1024',
    downloadIcns: 'ICNS (macOS)',
    downloadIco: 'ICO (Windows)',
    uploadHint: "Carica un'immagine per iniziare",
    dragCanvasHint: 'Clicca e trascina per posizionare',
    customColor: 'Colore personalizzato',
    coverRotation: 'Rotazione',
    removeImage: 'Rimuovi immagine',
    undo: 'Annulla',
    redo: 'Ripeti',
    section3: '3. Stili salvati',
    section3Hint: 'Salva i parametri grafici (etichetta, colori, font). L\'immagine non viene salvata.',
    savePreset: 'Salva stile',
    presetNamePlaceholder: 'Nome stile...',
    noPresets: 'Nessuno stile salvato',
    applyPreset: 'Applica',
    deletePreset: 'Elimina',
  },
  en: {
    subtitle: 'Create custom macOS folder icons.',
    section1: '1. Artwork',
    folderStyle: 'Folder style',
    folderColor: 'Folder color',
    cassetteColor: 'Cassette color',
    defaultColor: 'Default',
    changeImage: 'Change Image',
    uploadImage: 'Upload Image',
    uploadFormats: 'JPG, PNG, WEBP',
    zoom: 'Zoom',
    rotation: 'Rotation',
    section2: '2. Label',
    styleDymo: '🏷️ Dymo',
    styleBanner: '▬ Banner',
    styleBadge: '● Badge',
    labelText: 'Text (leave empty to hide)',
    labelPlaceholder: 'e.g. Project X',
    font: 'Font',
    fontSize: 'Text size',
    tapeSize: 'Tape size',
    badgeSize: 'Badge size',
    tapeAngle: 'Tape angle',
    resetTip: 'Reset',
    resetBtn: 'reset',
    dragHint: 'Drag the label on the preview to reposition it',
    colorTape: 'Tape Color',
    colorBanner: 'Banner Color',
    colorBadge: 'Badge Color',
    opacity: 'Opacity',
    download: 'Download',
    downloadPng: 'PNG 1024×1024',
    downloadIcns: 'ICNS (macOS)',
    downloadIco: 'ICO (Windows)',
    uploadHint: 'Upload an image to get started',
    dragCanvasHint: 'Click and drag to position',
    customColor: 'Custom color',
    coverRotation: 'Rotation',
    removeImage: 'Remove image',
    undo: 'Undo',
    redo: 'Redo',
    section3: '3. Saved Styles',
    section3Hint: 'Saves graphic parameters (label, colors, font). The image is not saved.',
    savePreset: 'Save style',
    presetNamePlaceholder: 'Style name...',
    noPresets: 'No saved styles',
    applyPreset: 'Apply',
    deletePreset: 'Delete',
  }
};

const FOLDER_COLORS = [
  { id: 'default', hex: null, name: 'Default' },
  { id: 'blue', hex: '#4B8EF0', name: 'Blu' },
  { id: 'purple', hex: '#9B6EE8', name: 'Viola' },
  { id: 'pink', hex: '#E86E9B', name: 'Rosa' },
  { id: 'red', hex: '#E85E5E', name: 'Rosso' },
  { id: 'orange', hex: '#E8924B', name: 'Arancione' },
  { id: 'yellow', hex: '#E8C84B', name: 'Giallo' },
  { id: 'green', hex: '#5EBF6E', name: 'Verde' },
  { id: 'gray', hex: '#8E8E93', name: 'Grigio' },
];

const CASSETTE_COLORS = [
  { id: 'default', hex: null, name: 'Default' },
  { id: 'black', hex: '#1a1a1a', name: 'Nero' },
  { id: 'white', hex: '#e8e4dc', name: 'Bianco' },
  { id: 'red', hex: '#c0392b', name: 'Rosso' },
  { id: 'blue', hex: '#2563a8', name: 'Blu' },
  { id: 'green', hex: '#27613a', name: 'Verde' },
  { id: 'yellow', hex: '#c8a832', name: 'Giallo' },
  { id: 'orange', hex: '#c0622b', name: 'Arancione' },
  { id: 'teal', hex: '#1a6b72', name: 'Teal' },
];

const CASSETTE_PNG_W = 2183;
const CASSETTE_PNG_H = 1417;
const CASSETTE_LABEL_X = 135;
const CASSETTE_LABEL_Y = 103;
const CASSETTE_LABEL_W = 1909;
const CASSETTE_LABEL_H = 929;

const FOLDERS = {
  classic: {
    id: 'classic',
    name: 'Classica',
    tintFolder: true,
    svg: "<svg width='1024' height='1024' version='1.1' vie